# Версия docker-compose
version: '2.4'

# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "8888:80"
#            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx

    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www

#    mysql:
#        image: mysql:8
#        ports:
#            - "3306:3306"
#        volumes:
#            - ./mysql:/var/lib/mysql
#        # задаем пароль для root пользователя
#        environment:
#            MYSQL_ROOT_PASSWORD: secret
