# Use postgres/example user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.19
    restart: always
    ports:
        - 9000:80
    volumes:
        - ./nginx:/etc/nginx/conf.d

  postgres:
    image: postgres:13
    restart: always
    volumes:
#      - ./data:/var/lib/postgresql/
      - /var/lib/postgresql/
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: example
      POSTGRES_DB: playdb


  python:
    build: ./python
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: gunicorn --bind 0.0.0.0:5000 manage:app
